pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.7.0'
}

def mekanismApDir = file('../Mekanism/annotation-processor')
if (mekanismApDir.exists()) {
    includeBuild(mekanismApDir.path) {
        dependencySubstitution {
            substitute module('mekanism.annotation-processor:annotation-processor') using project(':')
        }
    }
}